### ISSUE TITLE
Outdated?

### ISSUE THREAD

**Issue by zaceno** [hyperapp/awesome#18]
What is our stance on outdated entries? 

I think apps and boilerplates using older versions of hyperapp still have a place on the list, as they technically still work and may be of value as reference.

There are however some entries under the "Utilities" heading, which, by their own admission in their readmes, are "mixins". They won't work with recent versions of hyperapp. So what do we do with them? Take them out? Ask the author if they plan to update? Move them to an "Outdated" heading?

The entries in question (afaik) are:

- hyperapp-dot-notation-reducer
- hyperapp-firebase-auth
- hyperapp-hmr
- hyperapp-redux-devtools

**Comment by tobiasbueschel** [comment]
Good question @zaceno 👌 

I would perhaps ask authors whether they are planning to update and if we don't hear back or if they are not planning to do so, remove the respective entries.

IMHO, this awesome list is a place for people to find great (_awesome_) resources related to Hyperapp. Keeping the list up-to-date is therefore really import as the list becomes less helpful otherwise.

Therefore, I would vote for removing them or perhaps thinking about creating something like an archived list?

What do you think?

**Comment by zaceno** [comment]
@tobiasbueschel I would vote for an archival list at the bottom of the page I think, because those outdated projects might still inspire others to pick up the torch (or have some other cool idea).

We could @-mention of the author in the commit, to notify them of their "degradation" and perhaps inspire them to update their thing. 

Does anyone know how other awesome-lists do it?

It's good if we have a plan, but I don't think there's any rush, as things have been changing so rapidly lately, I have no idea what other things are still working, or in the process of being updated. Once 1.0 hits, and the api is *definitely* stable - *then* we should do a proper spring cleaning.

**Comment by JorgeBucaran** [comment]
@zaceno Any projects completely outdated that can be removed? and sorry, offtopic, but what about organizing `@hyperapp-*` separately from `hyperapp-*`?

**Comment by okwolf** [comment]
Now that 1.0.0 is out, by when do we want to remove/reorganize packages that are not compatible?

**Comment by rajaraodv** [comment]
Should we add an [outdated] tag to all those and start to remove them one by one after they are updated? 
@okwolf @JorgeBucaran

**Comment by JorgeBucaran** [comment]
@rajaraodv Or just remove it and create an issue on the original repository?

**Comment by okwolf** [comment]
I prefer @JorgeBucaran approach of removing projects that aren't compatible with 1.0.0 API.

**Comment by JorgeBucaran** [comment]
We need to go through the projects to check anyway, so let's do this:

1. Scan list.
2. Select the first project in top-down order.
3. Check if project is compatible with 1.0
4. If it is, proceed to the next item. Else, visit the repository and leave a note asking to please upgrade to 1.0.
5. Remove the project from this list.
6. Repeat until reaching the end of the list.

It's a shame we'll lose track of some of the cool projects on this list because there's a chance the authors will either not have time to upgrade or forget to report back if they did, but it's the most practical thing to do I can think of at the moment.

**Comment by okwolf** [comment]
@JorgeBucaran sounds like you have the steps pretty well defined, so have you written the bot to do it yet? 🤖

**Comment by JorgeBucaran** [comment]
Haha, okay I'll do it.

**Comment by zaceno** [comment]
FWIW my libs are 1.0 compatible, but my app example ("happy") is written with an older version. I've started rewriting it in 1.0 and fully intend to finish - but can't say how soon. So no need to tell me ;) and if you want to remove it for now that's fine. I can submit it again when I'm done porting it.

**Comment by JorgeBucaran** [comment]
If anyone is reading this before I actually go through the algorithm described [here](https://github.com/hyperapp/awesome/issues/18#issuecomment-354923491), could you please save me the trouble and update your project or remove from here? Once I start I'll turn into a wrecking ball. 😄

**Comment by okwolf** [comment]
@JorgeBucaran looks like this has been acted on. Should we close?
